// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbZ8UkjeIHmZdn4G3IWxn0_PsfBNb1ik8',
    appId: '1:249101398232:web:04f44c2340ff0c5655e7ad',
    messagingSenderId: '249101398232',
    projectId: 'iot-ta-796b8',
    authDomain: 'iot-ta-796b8.firebaseapp.com',
    databaseURL: 'https://iot-ta-796b8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iot-ta-796b8.appspot.com',
    measurementId: 'G-24YBN2QB8Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbW1phnHgbXZ2PmyVltxl1rImU_hMBXyA',
    appId: '1:249101398232:android:4a3298b20c404d2e55e7ad',
    messagingSenderId: '249101398232',
    projectId: 'iot-ta-796b8',
    databaseURL: 'https://iot-ta-796b8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iot-ta-796b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDA8IM_yTHAAp4S9S-zPCN0KkxL7_4kiEQ',
    appId: '1:249101398232:ios:c497052d14c7267c55e7ad',
    messagingSenderId: '249101398232',
    projectId: 'iot-ta-796b8',
    databaseURL: 'https://iot-ta-796b8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iot-ta-796b8.appspot.com',
    iosClientId: '249101398232-njvmk57vrhct6lrg9nr212adkb63gic0.apps.googleusercontent.com',
    iosBundleId: 'com.example.tugasakhir',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDA8IM_yTHAAp4S9S-zPCN0KkxL7_4kiEQ',
    appId: '1:249101398232:ios:c497052d14c7267c55e7ad',
    messagingSenderId: '249101398232',
    projectId: 'iot-ta-796b8',
    databaseURL: 'https://iot-ta-796b8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iot-ta-796b8.appspot.com',
    iosClientId: '249101398232-njvmk57vrhct6lrg9nr212adkb63gic0.apps.googleusercontent.com',
    iosBundleId: 'com.example.tugasakhir',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbZ8UkjeIHmZdn4G3IWxn0_PsfBNb1ik8',
    appId: '1:249101398232:web:d346ddd5efecda8355e7ad',
    messagingSenderId: '249101398232',
    projectId: 'iot-ta-796b8',
    authDomain: 'iot-ta-796b8.firebaseapp.com',
    databaseURL: 'https://iot-ta-796b8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iot-ta-796b8.appspot.com',
    measurementId: 'G-XNJH5YG1X9',
  );
}
